### ISSUE TITLE
Integration satoriAstro does not exsist?

### ISSUE THREAD

**Issue by bnjmnrsh** [florian-lefebvre/satori-astro#13]
Hi Florian,

I'm digging into this project as Im comparing OG image generator options for Astro. As I see it, `satoriAstro({...})` provides some very nice helper methods, a bit of a Swiss Army knife for Satori, very cool!

Im posting this issue because I've run into difficulty building and running the playground. I'm finding a call to an `satoriAstro()` integration in `astro.config.mjs`?  I've been looking for something that implements the type `AstroIntegration` but cant find it. Is this integration call an orphaned idea or is an example implementation in the works?

Many thanks btw for releasing this project I've learned a lot about the mono repo structure of  [astro-integration-template](https://github.com/florian-lefebvre/astro-integration-template)

**Comment by florian-lefebvre** [comment]
Hi, I'm glad it's useful to you!

Just to make sure I understand correctly the issue you're facing, you're having trouble running the playground in this repo?

**Comment by bnjmnrsh** [comment]
Hi Florian,
Yes when running the playground I encounter errors. I believe that this is because of this line in the config:

`import satoriAstro from "satori-astro";`

This is because "satori-astro" does not export a 'satoriAstro' method. It does export `satoriAstroOG`, but this is not an Astro integration.

This is the error that is thrown. 

```
[astro] Unable to load your Astro config

__vite_ssr_import_2__.default is not a function
  Location:
    /Users/anachronistic/Documents/WebDev/satori-astro-main/node_modules/.pnpm/vite@5.4.11_@types+node@20.17.9/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52972:5
  Stack trace:
    at /Users/anachronistic/Documents/WebDev/satori-astro-main/playground/astro.config.mjs:7:40
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by florian-lefebvre** [comment]
Thanks for reporting this, it should now be fixed!
