### ISSUE TITLE
satori-astro fails on Cloudflare Pages due to Node.js built-in module dependency

### ISSUE THREAD

**Issue by casungo** [florian-lefebvre/satori-astro#8]
I'm encountering a build failure when trying to use satori-astro on Cloudflare Pages. The error suggests that there's an issue with bundling the Node.js built-in "fs" module, which is being imported from the @resvg/resvg-js package, which is a dependency of satori-astro (
```
  satori-astro@0.0.1(astro@4.15.0(@types/node@22.5.1)(rollup@4.21.1)(typescript@5.5.4)):
    dependencies:
      '@resvg/resvg-js': 2.6.2
```
).

Error message:
```
[ERROR] [vite] x Build failed in 4.36s
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "fs" imported from "node_modules\.pnpm\@resvg+resvg-js@2.6.2\node_modules\@resvg\resvg-js\js-binding.js". Consider disabling ssr.noExternal or remove the built-in dependency.
```

This error occurs during the build process and prevents the successful deployment on Cloudflare Pages.

My astro config file:
```
import { defineConfig, envField } from "astro/config";

import cloudflare from "@astrojs/cloudflare";
import svelte from "@astrojs/svelte";
import auth from "auth-astro";
import tailwind from "@astrojs/tailwind";
import icon from "astro-icon";
import db from "@astrojs/db";
import i18n from "@astrolicious/i18n";
import satori from "satori-astro";

// https://astro.build/config
export default defineConfig({
  site: "xxxxxx",
  prefetch: true,
  integrations: [
    icon({
      include: {
        "material-symbols": ["translate-rounded", "dark-mode-rounded", "light-mode-rounded", "send-rounded", "info-rounded", "brightness-auto-rounded", "borg-rounded"],
        bxl: ["google"],
      },
    }),
    i18n({
      defaultLocale: "en",
      locales: ["en", "it", "es", "fr", "de"],
      client: {
        data: true,
        paths: true,
        translations: true,
      },
      sitemap: true,
    }),
    svelte(),
    auth(),
    tailwind(),
    db(),
    satori(),
  ],
  output: "server",
  adapter: cloudflare(),
  security: {
    checkOrigin: true,
  },
  vite: {
    ssr: {
      external: ["buffer", "path", "fs", "os", "async_hooks"].map((i) => `node:${i}`),
    },
  },
  experimental: {
    contentIntellisense: true,
    env: {
      schema: {
xxxx
      },
    },
  },
});
```

On Cloudflare Pages I set the compatibility flags to nodejs_compat, but it didn't change anything. Please advise since this is preventing me from pushing a SEO update. Thank you for your work anyways, it works perfectly in dev, its the build that is causing problems.

**Comment by casungo** [comment]
Update: The repository has been forked, and the code transitioned from resvg to svg2png-wasm. This change eliminates the need for Node, potentially resolving previous issues and possibly enhancing speed, although this has not been tested yet. I will create a PR to hear your thoughts.

**Comment by florian-lefebvre** [comment]
I didn't know resvg used `fs`, not sure what's the best option here 🤔. I guess you're using this package at runtime?

**Comment by florian-lefebvre** [comment]
Looks like we can't fix this...unless we swap `resvg` for another package! Maybe `sharp`?

**Comment by casungo** [comment]
Maybe... or something else entirely... I don't really have suggestions, I already implemented svg2png-wasm to try and see if cloudflare liked it (it didnt like it, got some weird errors). I could do a PR and maybe merge in a test branch and see if being installed from npm makes a difference rather that doing everything in a workspace. I also improved the playground, I can do a PR for that too :)

**Comment by florian-lefebvre** [comment]
PRs welcome! I'm experimenting with resvg wasm

**Comment by casungo** [comment]
great, now the project builds

but if i try to access the image i get this error:
i get this error
 ```
  "logs": [
    {
      "message": [
        "14:51:14 [ERROR] Error: Wasm has not been initialized. Call `initWasm()` function.\n    at new Resvg2 (pages/og/_lang_/_route_.png.astro.mjs:564:13)\n    at Object.toImage (pages/og/_lang_/_route_.png.astro.mjs:21257:14)\n    at async Object.toResponse (pages/og/_lang_/_route_.png.astro.mjs:21263:21)\n    at async Module.GET (pages/og/_lang_/_route_.png.astro.mjs:21410:10)\n    at async renderEndpoint (chunks/astro/server_D7qu0pls.mjs:72:20)\n    at async lastNext (chunks/_@astrojs-ssr-adapter_REKAsyNY.mjs:1269:23)\n    at async callMiddleware (chunks/_@astrojs-ssr-adapter_REKAsyNY.mjs:590:10)\n    at async RenderContext.render (chunks/_@astrojs-ssr-adapter_REKAsyNY.mjs:1308:22)\n    at async App.render (chunks/_@astrojs-ssr-adapter_REKAsyNY.mjs:2057:18)\n    at async Object.fetch (chunks/_@astrojs-ssr-adapter_REKAsyNY.mjs:2254:22)"
      ],
      "level": "error",
      "timestamp": 1725029474571
    }
  ],
```
